// app/tours/data.ts
export const tours = [
  {
    slug: "nanga-parbat-rupal-face-trek",
    image: "/images/nanga-parbat.jpg",
    title: "Nanga Parbat Rupal Face Trek | 2025 | BOOK NOW",
    duration: "09 Nights & 10 Days",
    reviews: 0,
  },
  {
    slug: "k2-base-camp-trek",
    image: "/images/k2-basecamp.jpg",
    title: "K2 Base Camp Trek | 2025 | BOOK NOW",
    duration: "20 Nights & 21 Days",
    reviews: 4,
  },
  {
    slug: "rakaposhi-diran-basecamp",
    image: "/images/rakaposhi.jpg",
    title: "Rakaposhi and Diran Base Camp Trek | 2025 | BOOK NOW",
    duration: "14 Days & 13 Nights",
    reviews: 0,
  },
  {
    slug: "k2-gondogoro-la-trek",
    image: "/images/gondogoro.jpg",
    title: "K2 Gondogoro La Trek | 2025 | BOOK NOW",
    duration: "20 Nights & 21 Days",
    reviews: 3,
  },
  {
    slug: "skardu-baltistan-valley-tour",
    image: "/images/skardu.jpg",
    title: "Skardu Baltistan Valley Tours | 2025 | BOOK NOW",
    duration: "13 Nights & 14 Days",
    reviews: 0,
  },
  {
    slug: "karakoram-highway-tour",
    image: "/images/karakoram-highway.jpg",
    title: "Karakoram Highway Tour | 2025 | BOOK NOW",
    duration: "17 Nights & 18 Days",
    reviews: 0,
  },
  {
    slug: "gilgit-baltistan-tour",
    image: "/images/gilgit-baltistan.jpg",
    title: "Gilgit Baltistan Tour | 2025 | BOOK NOW",
    duration: "14 Nights & 15 Days",
    reviews: 0,
  },
  {
    slug: "fairy-meadows-hunza-valley-tour",
    image: "/images/fairy-hunza.jpg",
    title: "Fairy Meadows and Hunza Valley Tour | 2025 | BOOK NOW",
    duration: "10 Nights & 11 Days",
    reviews: 0,
  },
  {
    slug: "gandhara-civilization-tour",
    image: "/images/gandhara.jpg",
    title: "Gandhara Civilization Tour | 2025 | BOOK NOW",
    duration: "09 Nights & 10 Days",
    reviews: 0,
  },
  {
    slug: "swat-valley-tour",
    image: "/images/swat-valley.jpg",
    title: "Swat Valley Tour | 2025 | BOOK NOW",
    duration: "05 Nights & 06 Days",
    reviews: 0,
  },
  {
    slug: "indus-valley-civilization-tour",
    image: "/images/indus-valley.jpg",
    title: "Indus Valley Civilization Tour | 2025 | BOOK NOW",
    duration: "11 Nights & 12 Days",
    reviews: 0,
  },
  {
    slug: "silk-road-explorers-tour",
    image: "/images/silk-road.jpg",
    title: "Silk Road Explorers Tour | 2025 | BOOK NOW",
    duration: "13 Nights & 14 Days",
    reviews: 0,
  },
];
