export const itineraries: Record<string, any> = {
  "nanga-parbat-rupal-face-trek": {
    title: "Nanga Parbat Rupal Face Trek",
    subtitle: "Rupal Face Adventure 2025",
    intro: [
      "Welcome to the majestic Nanga Parbat region!",
      "Experience thrilling adventures, breathtaking views, and unforgettable memories.",
    ],
    whatsapp: "923135235207",
    pdf: "/itinerary/nanga-parbat-rupal-face-trek.pdf",

    itinerariesByType: {
      /* ===================== BY AIR ===================== */
      air: [
        {
          day: "Day 01",
          title: "Arrival in Islamabad",
          hotel: "Best Western Premier Hotel Islamabad 5★ or similar",
          meals: "Dinner",
          points: [
            "Arrival at Islamabad International Airport",
            "Warm welcome & meet-and-greet",
            "Tour briefing",
            "Dinner and overnight stay in Islamabad",
          ],
        },
        {
          day: "Day 02",
          title: "Islamabad – Skardu – Gilgit",
          hotel: "Ramada by Wyndham Gilgit 5★ or similar",
          meals: "Breakfast / Lunch / Dinner",
          points: [
            "Early morning flight from Islamabad to Skardu",
            "Scenic aerial views of Karakoram Range and K2",
            "Visit Upper Kachura Lake (2,500m)",
            "Continue to Lower Kachura (Shangri-La Lake)",
            "Lunch at Tibet Restaurant",
            "Drive to Gilgit via Astak Nala, Rundo & Haramosh Valley",
            "Dinner and overnight stay in Gilgit",
          ],
        },
        {
          day: "Day 03",
          title: "Gilgit – Hunza Valley",
          hotel: "Ambiance Resort Hunza 5★ or similar",
          meals: "Breakfast / Lunch / Dinner",
          points: [
            "Drive from Gilgit to Hunza",
            "Stops at Guro Nala and Old Silk Road",
            "Rakaposhi View Point photography stop",
            "Lunch with views of Rakaposhi (7,788m)",
            "Visit historic Altit Fort (900+ years old)",
            "Dinner and overnight stay in Hunza",
          ],
        },
        {
          day: "Day 04",
          title: "Attabad Lake – Hussaini Bridge – Passu Cones",
          hotel: "Ambiance Resort Hunza 5★ or similar",
          meals: "Breakfast / Lunch / Dinner",
          points: [
            "Boating at Attabad Lake",
            "Visit Hussaini Suspension Bridge (399 steps)",
            "Photography at Passu Cones",
            "Lunch at Café de Khunjerab, Gircha",
            "Shopping at Sost Bazaar",
            "Return to Hunza for overnight stay",
          ],
        },
        {
          day: "Day 05",
          title: "Hunza – Nagar – Hopper Valley – Gilgit",
          hotel: "Ramada by Wyndham Gilgit 5★ or similar",
          meals: "Breakfast / Lunch / Dinner",
          points: [
            "Drive to Nagar Valley",
            "Stop at Nagar Proper (old capital)",
            "Visit Hopper Glacier",
            "Kaple Peak panoramic viewpoint",
            "Lunch at Kaple Restaurant",
            "Return drive to Gilgit",
            "Dinner and overnight stay",
          ],
        },
        {
          day: "Day 06",
          title: "Gilgit – Skardu",
          hotel: "Fortune North Resort Skardu 5★ or similar",
          meals: "Breakfast / Lunch / Dinner",
          points: [
            "Drive from Gilgit to Skardu",
            "Lunch at Astak Nala",
            "Visit Sarfaranga Cold Desert",
            "Visit Shigar Fort (17th century)",
            "Dinner and overnight stay in Skardu",
          ],
        },
        {
          day: "Day 07",
          title: "Skardu – Islamabad",
          hotel: "Best Western Premier Islamabad 5★ or similar",
          meals: "Breakfast / Lunch / Dinner",
          points: [
            "Flight from Skardu to Islamabad",
            "Visit Shah Faisal Mosque",
            "Visit Golra Sharif Railway Museum",
            "Shopping at F-6, F-7 & Safa Gold Mall",
            "Dinner and overnight stay in Islamabad",
          ],
        },
        {
          day: "Day 08",
          title: "Islamabad City Tour & Departure",
          hotel: "Drop-off",
          meals: "Breakfast / Lunch / Dinner",
          points: [
            "Visit Pakistan Monument",
            "Visit Lok Virsa Heritage Museum",
            "Lunch in Islamabad",
            "Shopping at Centaurus Mall",
            "Dinner and airport drop-off",
          ],
        },
      ],

      /* ===================== BY ROAD ===================== */
      road: [
        // SAME DATA — tum baad me road ke hisaab se change kar sakte ho
        {
    day: "Day 01",
    title: "Arrival in Islamabad",
    hotel: "Ramada by Wyndham Islamabad 4★",
    meals: "Dinner",
    points: [
      "Arrival at Islamabad International Airport",
      "Warm welcome & meet-and-greet by our team",
      "Tour briefing and assistance",
      "Dinner and overnight stay in Islamabad",
    ],
  },

  {
    day: "Day 02",
    title: "Islamabad City & Embassy Visit",
    hotel: "Ramada by Wyndham Islamabad 4★",
    meals: "Breakfast, Dinner",
    points: [
      "Breakfast at hotel",
      "Visit Indonesia Embassy in Islamabad for official meeting",
      "Meeting until evening",
      "Sightseeing tour of Islamabad",
      "Dinner and overnight stay in Islamabad",
    ],
  },

  {
    day: "Day 03",
    title: "Islamabad to Naran / Besham",
    hotel: "Rockwood Resort Naran 4★ / Besham Hilton Hotel 3★",
    meals: "Breakfast, Lunch, Dinner",
    points: [
      "Breakfast at hotel",
      "Drive towards Naran / Besham",
      "Sightseeing on the way through Abbottabad & Mansehra valleys",
      "Lunch at Balakot / Mansehra",
      "Short stays at Kiwai Waterfall, Paras Bridge & Shang Yaadgar",
      "Photography stops and valley views",
      "Dinner and overnight stay at Naran / Besham",
    ],
  },

  {
    day: "Day 04",
    title: "Naran / Besham to Gilgit via Babusar Pass",
    hotel: "Ramada by Wyndham Hotel Gilgit 5★",
    meals: "Breakfast, Lunch, Dinner",
    points: [
      "Breakfast at hotel",
      "Short stay at river rafting point",
      "Sightseeing at Batakundi, Baiser & Upper Kohistan valleys",
      "Visit Lulusar Lake & Babusar Top (13,700 ft)",
      "Lunch at Chillas (Fakher-e-Punjab Restaurant)",
      "Stops at Dasu Waterfall & Summer Nala",
      "Arrival in Gilgit",
      "Dinner and overnight stay in Gilgit",
    ],
  },

  {
    day: "Day 05",
    title: "Gilgit to Hunza Valley",
    hotel: "Ambiance Resort Hunza 5★",
    meals: "Breakfast, Lunch, Dinner",
    points: [
      "Breakfast at hotel",
      "Short stay at Guro Nala",
      "Drive along Old Silk Route",
      "Stop at Rakaposhi View Point",
      "Lunch at Rakaposhi View Point",
      "Visit Altit Fort",
      "Check-in at hotel",
      "Dinner and overnight stay in Hunza",
    ],
  },

  {
    day: "Day 06",
    title: "Hunza – Attabad Lake, Hussaini Bridge & Passu",
    hotel: "Ambiance Resort Hunza 5★",
    meals: "Breakfast, Lunch, Dinner",
    points: [
      "Breakfast at hotel",
      "Visit Attabad Lake (Boating / Jet Ski)",
      "Visit Hussaini Suspension Bridge",
      "Explore Passu Cones",
      "Drive to Sost",
      "Lunch at Café Khunjerab / Gircha",
      "Shopping at Sost Bazaar",
      "Return to Hunza",
      "Dinner and overnight stay in Hunza",
    ],
  },

  {
    day: "Day 07",
    title: "Hunza – Nagar Valley & Hopper Glacier",
    hotel: "Ramada by Wyndham Hotel Gilgit 5★",
    meals: "Breakfast, Lunch, Dinner",
    points: [
      "Breakfast at hotel",
      "Drive to Nagar Valley (Old State Capital)",
      "Photography stops in Nagar",
      "Visit Hopper Valley & Hopper Glacier",
      "Keple Peak View Point",
      "Lunch at Hopper",
      "Drive back to Gilgit",
      "Dinner and overnight stay in Gilgit",
    ],
  },

  {
    day: "Day 08",
    title: "Gilgit to Naran / Besham",
    hotel: "Rockwood Resort Naran 4★ / Besham Hilton Hotel 3★",
    meals: "Breakfast, Lunch, Dinner",
    points: [
      "Breakfast at hotel",
      "Stop at Three Mighty Mountains Junction Point",
      "Nanga Parbat View Point",
      "Lunch at Chillas",
      "Drive towards Naran / Besham",
      "Sightseeing and rest stops along the way",
      "Dinner and overnight stay at Naran / Besham",
    ],
  },

  {
    day: "Day 09",
    title: "Naran / Besham to Islamabad & Departure",
    hotel: "—",
    meals: "Breakfast, Lunch, Dinner",
    points: [
      "Breakfast at hotel",
      "Drive towards Islamabad",
      "Lunch at Balakot / Islamabad",
      "Visit Shah Faisal Mosque",
      "Visit Pakistan Monument & Lok Virsa Museum",
      "Shopping at F-6, F-7 Markets & Safa Gold Mall",
      "Dinner in Islamabad",
      "Transfer to Islamabad International Airport",
    ],
  },
      ],

      /* ===================== MIXED ===================== */
      mixed: [
        // SAME DATA — tum baad me mixed ke hisaab se change kar sakte ho
         {
    day: "Day 01",
    title: "Arrival in Islamabad",
    hotel: "Grand Islamabad Hotel 4★",
    meals: "Dinner",
    points: [
      "Arrival at Islamabad International Airport",
      "Warm welcome & meet-and-greet by our team",
      "Tour briefing and assistance",
      "Dinner and overnight stay in Islamabad",
    ],
  },

  {
    day: "Day 02",
    title: "Islamabad to Skardu (Flight)",
    hotel: "K2 Green Pak Resort Skardu 4★",
    meals: "Breakfast, Lunch, Dinner",
    points: [
      "Early morning breakfast at hotel",
      "Transfer to airport for flight to Skardu",
      "Scenic flight over the Karakoram Range (views of K2 and glaciers)",
      "Arrival in Skardu",
      "Visit Upper Kachura Lake",
      "Explore Soq Valley",
      "Lunch at Kachura",
      "Visit Lower Kachura Lake (Shangrila Lake)",
      "Drive to Skardu city",
      "Dinner and overnight stay in Skardu",
    ],
  },

  {
    day: "Day 03",
    title: "Skardu – Sarfaranga Cold Desert – Gilgit",
    hotel: "Ramada by Wyndham Hotel Gilgit 5★",
    meals: "Breakfast, Lunch, Dinner",
    points: [
      "Breakfast at hotel",
      "Visit Sarfaranga Cold Desert",
      "Adventure activities: Jeep Safari, Paragliding, Motor Riding, Horse Riding",
      "Visit historic Shigar Fort",
      "Lunch at Shigar",
      "Drive towards Gilgit",
      "Short stop at Astak Nala rest area",
      "Sightseeing of valleys and Rundo mining area",
      "Arrival in Gilgit",
      "Dinner and overnight stay in Gilgit",
    ],
    },
        {
    day: "Day 04",
    title: "Gilgit to Hunza Valley",
    hotel: "Famree Resort Hunza 4★",
    meals: "Breakfast, Lunch, Dinner",
    points: [
      "Breakfast at hotel",
      "Short stop at Guro Nala",
      "Drive along the Old Silk Route",
      "Lunch at Rakaposhi View Point",
      "Drive towards Hunza",
      "Visit Altit Fort",
      "Spend quality time exploring Altit Fort",
      "Check-in at hotel",
      "Dinner and overnight stay in Hunza",
    ],
  },

  {
    day: "Day 05",
    title: "Hunza – Attabad Lake, Hussaini Bridge & Passu",
    hotel: "Famree Resort Hunza 4★",
    meals: "Breakfast, Lunch, Dinner",
    points: [
      "Breakfast at hotel",
      "Visit Attabad Lake (Boating / Jet Ski)",
      "Visit Hussaini Suspension Bridge",
      "Explore Passu Cones",
      "Visit Rainbow Bridge",
      "Drive to Sost",
      "Lunch at Café Khunjerab / Gircha",
      "Shopping at Sost Bazaar",
      "Return to Hunza",
      "Dinner and overnight stay in Hunza",
    ],
  },

  {
    day: "Day 06",
    title: "Hunza – Nagar Valley – Hopper – Gilgit",
    hotel: "Kalisto Hotel Gilgit 3★",
    meals: "Breakfast, Lunch, Dinner",
    points: [
      "Breakfast at hotel",
      "Drive to Nagar Valley (Old State Capital)",
      "Photography stops in Nagar",
      "Drive to Hopper Valley",
      "Visit Hopper Glacier",
      "Keple Peak View Point",
      "Lunch at Keple Restaurant",
      "Drive back to Gilgit",
      "Short rest stop en route",
      "Dinner and overnight stay in Gilgit",
    ],
  },

  {
    day: "Day 07",
    title: "Gilgit to Naran / Besham",
    hotel: "Rockwood Resort Naran 4★ / Besham Hilton Hotel 3★",
    meals: "Breakfast, Lunch, Dinner",
    points: [
      "Breakfast at hotel",
      "Stop at Three Mighty Mountains Junction Point",
      "Nanga Parbat View Point",
      "Lunch at Fakhr-e-Punjab Restaurant / Shangrila Resort Chillas",
      "Drive towards Naran or Besham",
      "Scenic sightseeing and valley views",
      "Arrival at Naran / Besham",
      "Dinner and overnight stay",
    ],
  },

  {
    day: "Day 08",
    title: "Naran / Besham to Islamabad & Departure",
    hotel: "—",
    meals: "Breakfast, Lunch, Dinner",
    points: [
      "Breakfast at hotel",
      "Drive towards Islamabad",
      "Short rest stop en route",
      "Lunch in Islamabad",
      "Visit Pakistan Monument & Lok Virsa Museum",
      "Visit Shah Faisal Mosque",
      "Shopping at F-6 & F-7 Markets and Safa Gold Mall",
      "Dinner in Islamabad",
      "Transfer to Islamabad International Airport",
    ],
  },
      ],
    },
  },
};
